nelmio_api_doc:
    documentation:
        servers:
            - url: http://localhost:8876
        info:
            title: RickAndMorty
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!\.json$) # Accepts routes under /api except /api/doc
#    models: { use_jms: false }